apiVersion: v1
kind: Service
metadata:
  name: "dapr-scrapper-dispatcher-actor"
  labels:
    app: "scrapper-dispatcher-actor"
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "dapr-scrapper-dispatcher-actor"
  labels:
    app: "scrapper-dispatcher-actor"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "scrapper-dispatcher-actor"
  template:
    metadata:
      labels:
        app: "scrapper-dispatcher-actor"
      annotations:
        dapr.io/config: "tracing"
        dapr.io/enabled: "true"
        dapr.io/app-id: "scrapper-dispatcher-actor"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: "scrapper-dispatcher-actor"
        image: baio/eth-scrapper-dispatcher-actor
        ports:
        - containerPort: 3000
        imagePullPolicy: "Always"